# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://smcgown.com/"
title: SM
copyright: "© Steven McGown 2024"
paginate: 5
theme: [hugo-PaperMod, hugo-calendly-shortcode]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: About
          url: about/
          weight: 5
        - name: Blog
          url: blog/
          weight: 10
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Steven McGown
  # author: ["Me", "You"] # multiple authors
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: true

  profileMode:
    enabled: true
    title: Steven McGown
    imageUrl: "/images/profile.webp"
    imageTitle: ProfileMode image
    imageWidth: 200
    imageHeight: 200
    subtitle: "☁️ Cloud | 🤖 ML/AI | 🎶 Music | 📚 Research"
    buttons:
      - name: Blog
        url: blog
      - name: Résumé
        url: https://docs.google.com/document/d/1IyoHZTRtwr2IvqOf6wW-h1GtT6TARMPQi4DGGjKI9s8/edit?usp=sharing
      - name: Schedule a Meeting
        url: https://calendly.com/stevenmcgown1/meeting
  socialIcons:
    - name: github
      title: View my GitHub projects
      url: "https://github.com/stevenmcgown/"
    - name: Dev
      title: Check out my blog posts on Dev.to
      url: "https://dev.to/stevenmcgown"
    - name: LinkedIn
      title: Connect with me on LinkedIn!
      url: "https://www.linkedin.com/in/steven-mcgown/"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/stevenmcgown"
  # donateIcons:
  #   - name: KoFi
  #     title: Buy me a Ko-Fi :)
  #     url: "https://ko-fi.com/stevenmcgown"
  #   - name: Paypal
  #   - name: Monero
  #   - name: Bitcoin
  #   - name: Ethereum
  
  editPost:
    URL: "https://github.com/stevenmcgown/smcgown/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
      # favicon: "/images/favicon"
      # favicon16x16: "<link / abs url>"
      # favicon32x32: "<link / abs url>"
      # apple_touch_icon: "<link / abs url>"
      # safari_pinned_tab: "<link / abs url>"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
